# Generated by Django 5.0 on 2023-12-18 17:19

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_available_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=products.models.user_directory_path, verbose_name='Изображение'),
        ),
    ]
